BlogSystem/ViewModels/Admin/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BlogSystem.ViewModels.Admin
{
    public class LoginViewModel:PassBaseViewModel
    {
        [Required(ErrorMessage = "密码是必填项。")]
        [DataType(DataType.Password)]
        [Display(Name = "密码:")]
        public string Password { get; set; }
    }
}

BlogSystem/Controllers/AdminAccess/AdminLeaveMessageController.cs
using CommonObject.Constructs;
using CommonObject.Enums;
using ComponentsServices.Base;
using ComponentsServices.Mail.MailKit;
using BlogSystem.Base;
using BlogSystem.Models;
using BlogSystem.ViewModels.Admin;
using Microsoft.AspNetCore.Mvc;

namespace BlogSystem.Controllers.Admin
{

    /// <summary>
    /// 后台留言(评论回复)管理操作
    /// </summary>

    public class AdminLeaveMessageController : BaseAdminController
    {
        public static LeaveMessageViewModel slvm = new();
        private BaseSugar _baseSugar;
        private SugarDataBaseStorage<Article, int> _articleReader;
        private SugarDataBaseStorage<CommentCarryViewModel, int> _commentVmReader;
        private SugarDataBaseStorage<ReplyCarryViewModel, int> _replyVmReader;
        private SugarDataBaseStorage<AdminUser, int> _adminUserReader;
        private SugarDataBaseStorage<SiteSetting, int> _siteSettingReader;

        public AdminLeaveMessageController():base()
        {
            _baseSugar = new BaseSugar();
            _articleReader = new SugarDataBaseStorage<Article, int>(_baseSugar._dbHandler);
            _commentVmReader = new SugarDataBaseStorage<CommentCarryViewModel, int>(_baseSugar._dbHandler);
            _replyVmReader = new SugarDataBaseStorage<ReplyCarryViewModel, int>(_baseSugar._dbHandler);
            _adminUserReader = new SugarDataBaseStorage<AdminUser, int>(_baseSugar._dbHandler);
            _siteSettingReader = new SugarDataBaseStorage<SiteSetting, int>(_baseSugar._dbHandler);
        }

        /// <summary>
        /// 根据Id审核通过评论或回复
        /// </summary>
        /// <param name="id"></param>
        /// <param name="isPub">是来自已公开的评论或回复，因此不需要审核操作，而是直接回复或发送邮件，此参数兼容判断已公开的言论管理员需要回复</param>
        /// <returns></returns>
        [Route("{controller}/PassOneMsg")]
        [HttpPost]
        public async Task<IActionResult> DealOneNotPassOrPubMsg([FromBody] PassOneMsgViewModel vm, string? pt, bool isPub = false)
        {
            ValueResult result = new ValueResult { Code = ValueCodes.UnKnow };
            if (vm.Id < 1)
            {
                result.HideMessage = "DealOneNotPassOrPubMsg-操作评论或回复失败：id无效";
                result.TipMessage = "失败，请刷新重试";
                return Json(result);
            }
  
            SiteSetting siteSett = await _siteSettingReader.FirstOrDefaultAsync(s=>1==1);
            AdminUser adminUser = await _adminUserReader.FirstOrDefaultAsync(a=>a.AccountName==slvm.AccountName);
            
            if (vm.SupplyReply)
            {
                if (string.IsNullOrWhiteSpace(vm.Message))
                {
                    result.HideMessage = "DealOneNotPassOrPubMsg-操作评论或回复时附带回复信息，回复信息未填";
                    result.TipMessage = "附带回复请填写回复信息";
                    return Json(result);
                }
                if (siteSett == null)
                {
                    result.Code = ValueCodes.Error;
                    result.HideMessage = "DealOneNotPassOrPubMsg操作评论或回复时附带回复信息，SiteSetting表找不到";
                    result.TipMessage = "引发错误，请重新登录试试";
                    return Json(result);
                }
                if (string.IsNullOrWhiteSpace(siteSett.Domain))
                {
                    result.HideMessage = "DealOneNotPassOrPubMsg-操作评论或回复时附带回复信息，SiteSetting中域名没有填写需补充";
                    result.TipMessage = "请先去基本管理面板填写你的网站域名";
                    return Json(result);
                }
                if (adminUser == null)
                {
                    result.Code = ValueCodes.Error;
                    result.HideMessage = "DealOneNotPassOrPubMsg-操作评论或回复时附带回复信息，AdminUser表找不到当前管理员数据";
                    result.TipMessage = "引发错误，请重新登录试试";
                    return Json(result);
                }
                if (string.IsNullOrWhiteSpace(adminUser.Email))
                {
                    result.HideMessage = "DealOneNotPassOrPubMsg-操作评论或回复时附带回复信息，当前管理员没有设置邮箱";
                    result.TipMessage = "邮箱信息填写不全，请去邮箱设置面板进行设置。";
                    return Json(result);
                }
                // 需要抄送邮件，验证
                if (vm.SendEmail)
                {
                    // 判断EmailPassword是不是空足矣，因为邮箱设置必须全部填写完整才会更新数据表
                    if (string.IsNullOrWhiteSpace(adminUser.EmailPassword))
                    {
                        result.HideMessage = "DealOneNotPassOrPubMsg-操作评论或回复时抄送邮件，当前管理员没有设置邮箱";
                        result.TipMessage = "邮箱信息填写不全，请去邮箱设置面板进行设置。";
                        return Json(result);
                    }

                }
            }
            _baseSugar._dbHandler.BeginTran();
            string tmpMessagerName = "";
            string tmpMessagerEmail = "";
            string tmpAdmToMessagerContent = "";
            string tmpMessagerOrgContent = "";
            Article tmpMessagerRelatedArt;
            int opId = 0;
            try
            {
                if (vm.DType == 1)
                {
                    var cPassable = await _baseSugar._dbHandler.Queryable<Comment>().SingleAsync(c => c.Id == vm.Id);
                    // 不必判断isPub，无论是未审核的还是已公开的，全部更新IsPassed 不违背业务逻辑 减少多余代码判断
                    cPassable.IsPassed=true;
                    await _baseSugar._dbHandler.Updateable<Comment>(cPassable).ExecuteCommandAsync();
                    tmpMessagerName = cPassable.Name;
                    tmpMessagerEmail = cPassable.Email;
                    tmpMessagerOrgContent = cPassable.Content;
                    // 通过当前要处理通过的评论找到文章
                    tmpMessagerRelatedArt = await _articleReader.FindOneByIdAsync(cPassable.SourceId);
                    // 当前是审核评论 直接记录当前评论id
                    opId = vm.Id;
                }
                else
                {
                    var rPassable = await _baseSugar._dbHandler.Queryable<Reply>().SingleAsync(c => c.Id == vm.Id);
                    // 不必判断isPub，无论是未审核的还是已公开的，全部更新IsPassed 不违背业务逻辑 减少多余代码判断
                    rPassable.IsPassed = true;
                    await _baseSugar._dbHandler.Updateable<Reply>(rPassable).ExecuteCommandAsync();
                    tmpMessagerName = rPassable.Name;
                    tmpMessagerEmail = rPassable.Email;
                    tmpMessagerOrgContent = rPassable.Content;
                    // 通过当前要处理通过的回复找到评论
                    var relatedCmt = await _commentVmReader.FindOneByIdAsync(rPassable.CommentId);
                    // 通过评论找到文章
                    tmpMessagerRelatedArt = await _articleReader.FindOneByIdAsync(relatedCmt.SourceId);
                    // 当前是审核回复 记录当前回复对应的评论id
                    opId = relatedCmt.Id;
                }
                result.TipMessage = "已公开此条言论，会在评论区显示。";

                // 处理给这条内容附带回复
                if (vm.SupplyReply)
                {
                    Reply supReply = new Reply
                    {
                        CommentId = opId,
                        ReplyTime = DateTime.Now,
                        IsPassed = true,
                        IsAdmin = true,
                        ClientIp = "localhost",
                        Name = adminUser.AccountName,
                        Email = adminUser.Email,
                        SiteUrl = siteSett.Domain,
                    };
                    // 2回复某个回复，加上艾特符号；1回复评论，不用加
                    supReply.Content = vm.DType == 1 ? vm.Message : $"@{tmpMessagerName}：{vm.Message}";
                    tmpAdmToMessagerContent = supReply.Content;
                    await _baseSugar._dbHandler.Insertable<Reply>(supReply).ExecuteCommandAsync();
                    result.TipMessage = "已公开此条言论，会在评论区显示。且附带了你的回复。";
                }
                _baseSugar._dbHandler.CommitTran();
            }
            catch (Exception e)
            {
                _baseSugar._dbHandler.RollbackTran();
                result.Code = ValueCodes.Error;
                result.HideMessage = $"DealOneNotPassOrPubMsg-操作某{(vm.DType == 1 ? "评论" : "回复")}失败:" + e.Message;
                result.TipMessage = !isPub ?"通过失败请刷新重试": "给这条公开言论回复失败，请刷新重试";
                return Json(result);
            }
            result.Code = ValueCodes.Success;
            // 处理发送邮件提醒
            if (vm.SupplyReply&&vm.SendEmail&& adminUser != null)
            {
                try
                {
                    // send email
                    MailSendHelper mailSend = new MailSendHelper();
                    mailSend.InputSmtpServerHost(adminUser.SmtpHost, (int)adminUser.SmtpPort, (bool)adminUser.SmtpIsUseSsl);
                    mailSend.InputYourEmail(adminUser.AccountName, adminUser.Email);
                    mailSend.InputFriendEmail(tmpMessagerName, tmpMessagerEmail);
                    var t = tmpMessagerRelatedArt.IsShowTitle ?
                        !String.IsNullOrWhiteSpace(tmpMessagerRelatedArt.Title) ? tmpMessagerRelatedArt.Title : "无题链接" : "无题链接";
                    var n = !string.IsNullOrWhiteSpace(siteSett.SiteName) ? "-"+siteSett.SiteName : "";
                    var distinctionText = !isPub ? "，经过审核此条发言已被<i>公开</i>" : "，我对此进行了回复";
                    tmpAdmToMessagerContent = $"您在内容为<a href='{siteSett.Domain.TrimEnd('/')}/Detail?articleId={tmpMessagerRelatedArt.Id}'><b>{t}</b></a>上进行了发言" +
                        $"{distinctionText}，并且特意向您抄送这封邮件已表达我对此的兴趣。我的回复内容如下：" +
                        $"<br><p><mark>{tmpAdmToMessagerContent}</mark></p><br>您的发言原内容：<br><small>{tmpMessagerOrgContent}</small>" +
                        $"<br>您使用的昵称为：<small>{tmpMessagerName}</small>" +
                        $"<br><br>--该邮件为系统自动发送请勿回复--<br>--若您没有上述操作请忽略此邮件--";
                    mailSend.InputContent("发言收到了博主回应" + n, tmpAdmToMessagerContent, true);
                    mailSend.SendByAuthenticate(adminUser.Email, adminUser.EmailPassword);
                    result.TipMessage = result.TipMessage+"且邮件已发送给此网友。";
                }
                catch (Exception e)
                {

BlogSystem/Controllers/AdminAccess/AdminSiteSettingController.cs
using ComponentsServices.Base;
using BlogSystem.Base;
using BlogSystem.Models;
using BlogSystem.ViewModels.Admin;
using Microsoft.AspNetCore.Mvc;

namespace BlogSystem.Controllers.AdminAccess
{
    /// <summary>
    /// 后台基本配置操作
    /// </summary>
    public class AdminSiteSettingController : BaseAdminController
    {
        private SugarDataBaseStorage<SiteSetting, int> _siteSettingSet;

        public AdminSiteSettingController() : base()
        {
            _siteSettingSet = new SugarDataBaseStorage<SiteSetting, int>();
        }

        /// <summary>
        /// 移除有些场景下表单不需要验证的属性
        /// </summary>
        private void RemoveSomeValid()
        {
            ModelState.Remove("AccountName");

        }

        /// <summary>
        /// 更新站点的基本配置
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> EditSiteSetting(SiteSettingViewModel vm)
        {
            RemoveSomeValid();

            if (vm is null)
            {
                ModelState.AddModelError("", "更新失败:传递获取不到模型，重启浏览器再试吧？。");
                return View(vm);
            }
            vm = (SiteSettingViewModel)WrapMustNeedPassFields(vm);
            if (vm.OnePageCount<=0)
            {
                ModelState.AddModelError("", "更新失败:主页列表展示文章的条数不能是0。");
                return View(vm);
            }

            SiteSetting saveEntity = new SiteSetting
            {
                SiteName = vm.SiteName,
                IsShowSiteName = vm.IsShowSiteName,
                IsShowQutoes = vm.IsShowQutoes,
                Cban = vm.Cban,
                Domain = vm.Domain,
                FashionQuotes = vm.FashionQuotes,
                Host = vm.Host,
                TailContent = vm.TailContent,
                OnePageCount = vm.OnePageCount,
                LoginUriValue = vm.LoginUriValue,
                IsShowEdgeSearch = vm.IsShowEdgeSearch,
                IsOpenDetailThumb = vm.IsOpenDetailThumb,
                LeaveLimitCount = vm.LeaveLimitCount,
            };

            _siteSettingSet.TransBegin();
            try
            {
                // 虽然是全删除 但也只有一个站点数据
                await _siteSettingSet._dbHandler.Deleteable<SiteSetting>().Where(s=>1==1).ExecuteCommandAsync();
                await _siteSettingSet.InsertAsync(saveEntity);
                _siteSettingSet.TransCommit();
            }
            catch (Exception)
            {
                _siteSettingSet.TransRoll();
                ModelState.AddModelError("", "更新失败回滚，重启浏览器再试吧？。");
                return View(vm);
            }
            return RedirectToAction("AdminHome", "Admin", new { pt = vm.PassToken });

        }

        /// <summary>
        /// 站点的基本配置修改页面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> EditSiteSetting(string? pt)
        {
           var eny =  await _siteSettingSet._dbHandler.Queryable<SiteSetting>().FirstAsync();
            SiteSettingViewModel org = new SiteSettingViewModel
            {
                SiteName = eny.SiteName,
                IsShowSiteName = eny.IsShowSiteName,
                IsShowQutoes = eny.IsShowQutoes,
                Cban = eny.Cban,
                Domain = eny.Domain,
                FashionQuotes = eny.FashionQuotes,
                Host = eny.Host,
                OnePageCount = eny.OnePageCount,
                TailContent = eny.TailContent,
                LoginUriValue = eny.LoginUriValue,
                IsShowEdgeSearch = eny.IsShowEdgeSearch,
                IsOpenDetailThumb = eny.IsOpenDetailThumb,
                LeaveLimitCount = eny.LeaveLimitCount,
            };
            // 自动封装已有的数据
            org = (SiteSettingViewModel)WrapMustNeedPassFields(org);
            return View(org);
        }
    }
}

BlogSystem/Views/AdminAccess/Admin/AdminHome.cshtml
@model PassBaseViewModel

<input hidden id="pt" value="@Model.PassToken"/>
<input hidden id="accountName" value="@Model.AccountName"/>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">菜单设置</h5>
    <p class="card-text">管理你的菜单，给菜单设置名称、顺序..</p>

    <a class="btn btn-primary" asp-route-pt="@Model.PassToken" asp-action="MenuAmManagement" asp-controller="AdminMenu">前往</a>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">文章管理</h5>
    <p class="card-text">发表、操作文章，归类和加锁..</p>
    <a  class="btn btn-primary" asp-route-pt="@Model.PassToken" asp-action="ArticleAmManagement" asp-controller="AdminArticle">前往</a>
  </div>
</div>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">文件图片</h5>
    <p class="card-text">上传文件链接，或上传图片来插入文章、以及自定义链接..</p>
    <a  class="btn btn-primary" asp-route-pt="@Model.PassToken" asp-action="FileAmManagement" asp-controller="AdminFile">前往</a>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">站点设置</h5>
    <p class="card-text">基本的配置，包含站点名称、签名以及尾部内容、个性化管控..</p>
    <a  class="btn btn-primary" asp-route-pt="@Model.PassToken" asp-action="EditSiteSetting" asp-controller="AdminSiteSetting">前往</a>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">留言管理</h5>
    <p class="card-text">管理内容的评论、回复，审核它们，回复留言者以及邮件通知..</p>
    <a  class="btn btn-primary" asp-route-pt="@Model.PassToken" asp-action="LeaveNotPassAmManagement" asp-controller="AdminLeaveMessage">未审核的</a>
    <a  class="btn btn-primary" asp-route-pt="@Model.PassToken" asp-action="LeavePublicAmManagement" asp-controller="AdminLeaveMessage">已公开的</a>
  </div>
</div>
<p class="placeholder-glow">
  <span class="placeholder col-12"></span>
</p>
<div>
    <p>
      <a class="btn btn-secondary btn-sm" data-bs-toggle="collapse" href="#collapseMore" role="button" aria-expanded="false" aria-controls="collapseMore">
        邮箱配置⬇
      </a>
    </p>
    <div class="collapse" id="collapseMore">
      <div class="card card-body">
          <p>请查阅您使用的邮箱服务提供商的SMTP相关文档说明。通常邮箱账户即您的发信Email账户，授权密码即邮箱密码。但诸如QQ邮箱需要使用授权码而不是QQ邮箱密码。</p>
      </div>
      <div class="card card-body">
        <div class="row">
            <input style="width:50%" id="email" nmae="Email" maxlength="25" type="email" class="form-control" placeholder="邮箱账户x@@x.x">
            <input style="width:50%" id="emailPassword" nmae="EmailPassword" maxlength="32" type="password" class="form-control" placeholder="smtp授权密码">
        </div>
        <div class="row">
            <input style="width:50%" id="smtpHost" nmae="SmtpHost" maxlength="12" type="text" class="form-control" placeholder="smtp服务地址">
            <input style="width:50%" id="smtpPort" nmae="SmtpPort" maxlength="6" type="number" class="form-control" placeholder="Smtp服务端口">
        </div>
        <div class="row">
            <input class="col-1 form-check-input" id="smtpIsUseSsl" type="checkbox" checked nmae="SmtpIsUseSsl">
            <label class="col-11 form-check-label" for="smtpIsUseSsl">Smtp邮箱服务是否必须使用ssl</label>
        </div>
        <div class="row">
            <div class="col-3">
                <button class="btn btn-primary btn-sm" type="button" onclick="smtpEmailServerUp()">确认</button>
            </div>
            <div class="col-9"></div>
        </div>
      </div>
    </div>
</div>

<script>
    // ajax调用更改当前管理员账号的邮箱smtp服务信息
    function smtpEmailServerUp(){
        var pt = $('#pt').val();
        var accountName = $('#accountName').val();
        var email = $('#email').val();
        var emailPassword = $('#emailPassword').val();
        var smtpHost = $('#smtpHost').val();
        var smtpPort = parseInt($('#smtpPort').val());
        if(isNaN(smtpPort))
            return;
        var smtpIsUseSsl = $('#smtpIsUseSsl').prop("checked");
        var url = "/Admin/UpSmtpEmailInfo?pt="+pt;
        $.ajax (
            {
                url: url,
                type: "POST",
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify({
                    "Email":email,
                    "AccountName":accountName,
                    "EmailPassword":emailPassword,
                    "SmtpHost":smtpHost,
                    "SmtpPort":smtpPort,
                    "SmtpIsUseSsl":smtpIsUseSsl
                }),
                success: function(data, status){
                    if(data['code']==1){
                        Gb_NotifShow("更改成功-配置已存储");
                    }else{
                        Gb_NotifShow(data['tipMessage'],"primary");
                    }
                },
                error: function(err){
                    Gb_NotifShow("更改失败err","danger");
                    console.log(err)
                }
            }
        );
    }
</script>

BlogSystem/Views/AdminAccess/Admin/Login.cshtml
@model LoginViewModel
<div asp-validation-summary="All" class="text-danger">
</div>
<form method="post">
    <div class="form-group">
        <label asp-for="AccountName"></label>
        <input asp-for="AccountName" type="text" class="form-control">
        <span asp-validation-for="AccountName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" type="password" class="form-control">
        <span asp-validation-for="Password" class="text-danger"></span>
    </div>
    <div class="btn-group" role="group" aria-label="Basic example">
        <button  asp-action="Login" asp-controller="Admin" type="submit" class="btn btn-primary">登录</button>
    </div>
    <p>
    <a class="btn btn-dark" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    修改密码
    </a>
    </p>
</form>
<!--collapseExample 隐藏元素-->
<div class="collapse" id="collapseExample">
    <div class="card card-body">
        <form method="post">
        <div class="form-group">
        <label name="OrgAccountName">原管理员昵称</label>
        <input name="OrgAccountName" type="text" class="form-control" value="">
        </div>
        <div class="form-group">
        <label name="OrgPassword">原密码</label>
        <input name="OrgPassword" type="password" class="form-control" value="">
        </div>
        <div class="form-group">
        <label name="NewAccountName">新管理员昵称</label>
        <input name="NewAccountName" type="text" class="form-control" value="">
        </div>
        <div class="form-group">
        <label name="NewPassword">新密码</label>
        <input name="NewPassword" type="password" class="form-control" value="">
        </div>
        <div class="form-group">
        <label name="NewPasswordRep">再次输入新密码</label>
        <input name="NewPasswordRep" type="password" class="form-control" value="">
        </div>
        <div class="form-group">
        <label name="Email">邮箱</label>
        <input name="Email" type="email" class="form-control" value="">
        </div>
        <button type="submit" class="btn btn-dark" asp-action="Reset" asp-controller="Admin">确认修改</button>
        </form>
    </div>
</div>