BlogSystem/ViewModels/Home/HomeArticleViewModel.cs
using BlogSystem.Models;
using SqlSugar;

namespace BlogSystem.ViewModels.Home
{
    /// <summary>
    /// 前台文章 模型视图类
    /// </summary>
    public class HomeArticleViewModel:Article
    {
        /// <summary>
        /// 当前文章关联的菜单实体  非字段 只用于显示
        /// </summary
        [SugarColumn(IsIgnore = true)]
        public Menu RelatedMenu { get; set; } = new Menu();
    }
}

BlogSystem/ViewModels/Home/HomeMenuViewModel.cs
using BlogSystem.Models;

namespace BlogSystem.ViewModels.Home
{
    /// <summary>
    /// 主页前台 菜单 模型视图类
    /// </summary>
    public class HomeMenuViewModel
    {   
        public int Id { get; set; }
        public string Name { get; set; }
        public int PId { get; set; }

        public bool IsHome { get; set; }
        public bool IsShow { get; set; }
        public int OrderNumber { get; set; }
        public string? Tips { get; set; }


        /// <summary>
        /// 下级菜单
        /// </summary>
        public List<HomeMenuViewModel> Subs { get; set; } = new List<HomeMenuViewModel>();

    }
}

BlogSystem/ViewModels/Home/HomeSiteSettingViewModel.cs
using BlogSystem.Models;

namespace BlogSystem.ViewModels.Home
{
    /// <summary>
    /// 前台主页所需全局展示基本配置数据 继承自实体模型
    /// </summary>
    public class HomeSiteSettingViewModel: SiteSetting
    {
    }
}

BlogSystem/ViewModels/Home/HomeViewModel.cs
using BlogSystem.Models;
using BlogSystem.ViewModels.Detail;

namespace BlogSystem.ViewModels.Home
{
    /// <summary>
    /// 主页所需展示视图模型
    /// </summary>
    public class HomeViewModel
    {
        /// <summary>
        /// 全局视图所需的全局菜单数据
        /// </summary>
        public List<HomeMenuViewModel> HomeMenusData { get; set; } = new List<HomeMenuViewModel>();
        /// <summary>
        /// 全局视图所需的全局基本配置数据
        /// </summary>
        public HomeSiteSettingViewModel HomeSiteSettingData { get; set; } = new HomeSiteSettingViewModel();

        /// <summary>
        /// 分页列表视图所需用到的文章列表的视图模型类
        /// </summary>
        public List<HomeArticleViewModel> HomeArticleViewModels { get; set; } = new List<HomeArticleViewModel>();
        /// <summary>
        /// 显示当前浏览的菜单、搜索结果提示，但基本主页分页浏览不显示
        /// </summary>
        public string LocationTip { get; set; } = "";
        public string Location { get; set; } = "";
        /// <summary>
        /// 找不到文章的提示
        /// </summary>
        public string NotTips { get; set; } = "";
        /// <summary>
        /// 当前网页需要显示的title 首页是站点名 文章是文章标题 文章不显示标题仍是站点名
        /// </summary>
        public string CurrentTitle { get; set; } = "";

        /// <summary>
        /// 是否没有设置显示任何一个侧边栏组件
        /// </summary>
        public bool IsNotShowAnyOneCom { get; set; } = false;

        /// <summary>
        /// 分页计数
        /// </summary>
        public PageCompute PageCompute { get; set; } = new PageCompute();


        /// <summary>
        /// 此为某篇文章详细的视图模型类
        /// </summary>
        public DetailArticleViewModel? DetailArticleData { get; set; } = new DetailArticleViewModel();

    }
    public class PageCompute
    {
        public int PageIndex { get; set; } = 1;
        public int NextIndex { get; set; } = 1;
        public int PreIndex { get; set; } = 1;
        public bool ShowPreIndex { get; set; } = false;
        public bool ShowNextIndex { get; set; } = false;
        public int PagesChangeMax { get; set; } = 1;
    }
}

BlogSystem/Controllers/DetailController.cs
using BlogSystem.Base;
using BlogSystem.Bll;
using BlogSystem.ViewModels.Detail;
using Microsoft.AspNetCore.Mvc;

namespace BlogSystem.Controllers.Home
{
    /// <summary>
    /// 文章帖子详细页面控制器
    /// </summary>
    public class DetailController : BaseController
    {
        private readonly ILogger<DetailController> _logger;
        private readonly DetailLogicBll _detailBll;

        public DetailController(ILogger<DetailController> logger) : base()
        {
            _logger = logger;
            _detailBll = new DetailLogicBll();
            WrapsGlobalHomeData();
        }
        [Route("{Controller}/")]
        [Route("{Controller}/{custUri}")]
        public async Task<IActionResult> Index(int? articleId, string? custUri)
        {
            await _detailBll.DealArticleEntityAsync(_homeGlobalView, articleId, custUri);
            return View(_homeGlobalView);
        }

        /// <summary>
        /// 加锁文章解锁接口
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        /// 指定路由为{Controller}/UnLock/ArticleUnLock，否则{Controller}/ArticleUnLock直接走Index方法自定义文章uri了
        [HttpPost]
        [Route("{Controller}/UnLock/ArticleUnLock")]
        public JsonResult ArticleUnLock([FromBody]DetailArticleUnLockViewModel data)
        {
            var res = _detailBll.DealArticleUnLock(data);
            return new JsonResult(res);
        }
    }
}

BlogSystem/Controllers/HomeController.cs
using BlogSystem.Base;
using BlogSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BlogSystem.Controllers.Home
{
    /// <summary>
    /// 主页前台展示控制
    /// </summary>
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger):base()
        {
            _logger = logger;
            WrapsGlobalHomeData();
        }

        /// <summary>
        /// 主页索引 展示具体分页数据
        /// </summary>
        /// <param name="from">点击来源 菜单|外链</param>
        /// <param name="menuId">点击来源的具体值 菜单是菜单id ..</param>
        /// <param name="kw">点击来源的具体值 搜索是关键字..</param>
        /// <param name="pageIndex">分页码</param>
        /// <param name="onePageCount">每页文章条数</param>
        /// <returns></returns>
        public async Task<IActionResult> Index(string? from, int? menuId,string? kw, int pageIndex=1, int onePageCount=5)
        {
            _homeGlobalView.CurrentTitle = _homeGlobalView.HomeSiteSettingData.SiteName;
            // 从配置里取设置的每页条数
            onePageCount = _homeGlobalView.HomeSiteSettingData.OnePageCount<=0?
                onePageCount: _homeGlobalView.HomeSiteSettingData.OnePageCount;
            // 跳到当前页 获取文章列表
            int c = await DealFilterData(from, menuId, kw, pageIndex, onePageCount);
            
            // 根据文章MenuId获取每篇文章所属菜单名
            foreach (var item in _homeGlobalView.HomeArticleViewModels)
            {
                item.Ig_MenuName = (await bdb._dbHandler.Queryable<Menu>().FirstAsync(m => m.Id == item.MenuId))?.Name ?? "未知菜单";
            }
            ComputePage(c, pageIndex, onePageCount);

            return View(_homeGlobalView);
        }
    }
}

BlogSystem/Views/Home/Index.cshtml
@model HomeViewModel
<!--主页文章列表视图 包含分页-->


<!--文章列表-->
@foreach (var item in Model?.HomeArticleViewModels)
{
<div class="card text-center">
<div class="card-body">
@if (item.IsShowTitle)
{
<h4 class="card-title ">@item.Title</h4>
}
<p class="card-text"><span class="badge rounded-pill bg-light text-dark">摘要</span>@(item.Abstract)...</p>
@if (!string.IsNullOrWhiteSpace(@item.CustUri))
{   
    // 若自定义uri不为空 指定uri获取文章，否则，用文章Id
    <a class="btn btn-outline-dark" asp-route-custUri="@item.CustUri" asp-controller="Detail" asp-action="Index" >阅读更多</a>
}else{
    <a class="btn btn-outline-dark" asp-route-articleId="@item.Id" asp-controller="Detail" asp-action="Index" >阅读更多</a>
}
</div>
<div class="card-footer text-muted"><span class="badge bg-success">@(item.Ig_MenuName)</span> <small class="text-primary"><span class="badge rounded-pill bg-info text-dark">更新于@(item.UpdateTime.ToString("yyyy-MM-dd HH:mm:ss"))</span></small>
@if (item.IsLock)
{
    <svg t="1645106164793" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1873" width="16" height="16"><path d="M512 170.666667c70.314667 0 128 57.685333 128 128v128H384V298.666667c0-70.314667 57.685333-128 128-128z m213.333333 256V298.666667c0-117.418667-95.914667-213.333333-213.333333-213.333334S298.666667 181.248 298.666667 298.666667v128H256a85.333333 85.333333 0 0 0-85.333333 85.333333v341.333333a85.333333 85.333333 0 0 0 85.333333 85.333334h512a85.333333 85.333333 0 0 0 85.333333-85.333334v-341.333333a85.333333 85.333333 0 0 0-85.333333-85.333333h-42.666667zM256 512h512v341.333333H256v-341.333333z" fill="#d4237a" p-id="1874"></path></svg>
}    
</div>
</div>
}
<!--分页-->
<div class="row">
<nav aria-label="...">
<ul class="pagination">
<li class="page-item">
    <button class="page-link" role="button" id="pageChangeMaxLinkBtn">页选择</button>
</li>
<li class="page-item @(Model.PageCompute.ShowPreIndex?"":"disabled")">
    @{
        //获取上下文查询参数 直接传递当前from参数的值 且获取menuId和kw关键字的值，因为当前是菜单分页的话，kw就是null，反之亦然，控制器逻辑已经判断
    }
    <a class="page-link" asp-route-from="@Context.Request.Query["from"].FirstOrDefault()" asp-route-menuId="@Context.Request.Query["menuId"].FirstOrDefault()" asp-route-kw="@Context.Request.Query["kw"].FirstOrDefault()" asp-action="Index" asp-controller="Home" asp-route-PageIndex="@Model.PageCompute.PreIndex">上翻</a>
</li>
<li class="page-item"><a class="page-link text-black-50">@Model.PageCompute.PageIndex</a></li>
<li class="page-item @(Model.PageCompute.ShowNextIndex?"":"disabled")">
    <a class="page-link" asp-route-from="@Context.Request.Query["from"].FirstOrDefault()" asp-route-menuId="@Context.Request.Query["menuId"].FirstOrDefault()" asp-route-kw="@Context.Request.Query["kw"].FirstOrDefault()" asp-action="Index" asp-controller="Home" asp-route-PageIndex="@Model.PageCompute.NextIndex">下翻</a>
</li>
</ul>
</nav>
</div>
<!--页选择模态-->
<div class="modal fade" id="pagesChangeMaxModel"  aria-labelledby="pagesChangeMaxModel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">当前结果下跳转页</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        @for (var i = 1; i <= Model.PageCompute.PagesChangeMax; i++)
        {
            <a class="list-group-item text text-primary" asp-route-from="@Context.Request.Query["from"].FirstOrDefault()" asp-route-menuId="@Context.Request.Query["menuId"].FirstOrDefault()" asp-route-kw="@Context.Request.Query["kw"].FirstOrDefault()" asp-action="Index" asp-controller="Home" asp-route-PageIndex="@i">第@(i)页</a>
        }
      </div>
    </div>
  </div>
</div>
<script src="~/js/view/Home/Index.js?v=0405"></script>